spring:
  application:
    name: "api-gateway"
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  zipkin:
    base-url: http://192.168.86.130:9411

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true

#logging:
#  level:
#    root: debug

redis:
  host: http://192.168.86.130
  port: 6379
