spring:
  application:
    name: "api-gateway"
  config:
    import: "optional:configserver:http://192.168.86.130:8888/"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  zipkin:
    base-url: http://192.168.86.130:9411
  sleuth:
      sampler:
        probability: 1

#logging:
#  level:
#    root: debug

redis:
  host: http://192.168.86.130
  port: 6379
