
spring:
  application:
    name: "api-gateway"
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        uri: https://spring.io
        predicates:
          -Path=/guides
        filters:
          -name: RequestRateLimiter
          args:
            radis-rate-limiter.replenisRate: 2
            radis-rate-limiter.burstCapacity: 2




#logging:
#  level:
#    root: debug

redis:
  host: localhost
  port: 6379