spring:
  application:
    name: "api-gateway"
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

#logging:
#  level:
#    root: debug

redis:
  host: localhost
  port: 6379