spring:
  application:
    name: "book-service"
  config:
    import: "optional:configserver:http://192.168.86.130:8888/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
#  eureka.instance.instance-eureka.instance.instance-id=eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
# SET IP ADDRESS IF IT IS NOT AUTOMATICALLY PICKED UP AND SHOWN WHEN CLICKING ON THE INSTANCE LINK ON THE EUREKA DISCOVERY SERVER
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.17.0.2 # docker ip address
  client:
    serviceUrl:
      defaultZone: http://192.168.86.130:8761/eureka/